In [22]:
import pandas as pd

In [23]:
# Reading Files
file_path1 = r'C:\\Users\\Sheewakoti_Manish\\Documents\\My-Codes\\Sharp-Blue-Tasks\\Day01\\Task1\\data\\UNLOCODE CodeListPart1.csv'
file_path2 = r'C:\\Users\\Sheewakoti_Manish\\Documents\\My-Codes\\Sharp-Blue-Tasks\\Day01\\Task1\\data\\UNLOCODE CodeListPart2.csv'
file_path3 = r'C:\\Users\\Sheewakoti_Manish\\Documents\\My-Codes\\Sharp-Blue-Tasks\\Day01\\Task1\\data\\UNLOCODE CodeListPart3.csv'

In [24]:
# Displaying the Contents in First File
df1 = pd.read_csv(file_path1)
df1

,Unnamed: 0,AD,Unnamed: 2,.ANDORRA,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,AD,ALV,Andorra la Vella,Andorra la Vella,NaN,--34-6--,AI,601.0,NaN,4230N 00131E,NaN
1,NaN,AD,CAN,Canillo,Canillo,NaN,--3-----,RL,307.0,NaN,4234N 00135E,NaN
2,NaN,AD,EAC,Escàs,Escas,04,--3-----,RL,1407.0,NaN,4233N 00131E,NaN
3,NaN,AD,ENC,Encamp,Encamp,NaN,--3-----,RL,307.0,NaN,4232N 00134E,NaN
4,NaN,AD,ESC,Escaldes-Engordany,Escaldes-Engordany,NaN,--3-----,RL,307.0,NaN,4231N 00133E,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
54833,NaN,FR,ZZU,Carnoules,Carnoules,83,1----6--,RL,1901.0,NaN,4318N 00611E,NaN
54834,NaN,FR,ZZW,Zellwiller,Zellwiller,67,-----6--,RL,1901.0,NaN,4824N 00730E,NaN
54835,NaN,FR,ZZX,Heiltz-le-Hutier,Heiltz-le-Hutier,51,--3-----,RL,1401.0,NaN,4841N 00446E,NaN
54836,NaN,FR,ZZY,Douzy,Douzy,08,--3-----,RL,1101.0,NaN,4940N 00503E,NaN
54837,NaN,FR,ZZZ,Saint-Pierre-des-Landes,Saint-Pierre-des-Landes,53,--3-----,RL,1701.0,NaN,4816N 00101W,NaN

In [25]:
# Displaying the contents in Second File
df2 = pd.read_csv(file_path2)
df2

,Unnamed: 0,GA,Unnamed: 2,.GABON,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,GA,AKE,Akieni,Akieni,NaN,---4----,AI,9601.0,NaN,NaN,NaN
1,NaN,GA,AWE,Alowe,Alowe,NaN,---4----,RL,901.0,NaN,0045S 00927E,NaN
2,NaN,GA,BEL,Belleville,Belleville,NaN,--3-----,RL,607.0,NaN,0002N 01102E,NaN
3,NaN,GA,BGB,Booué,Booue,NaN,---4----,AI,212.0,NaN,0006S 01156E,NaN
4,NaN,GA,BMM,Bitam,Bitam,NaN,---4----,AI,9601.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
27691,NaN,NZ,WYH,Wyndham,Wyndham,STL,--3-----,RL,607.0,NaN,4619S 16851E,NaN
27692,NaN,NZ,WYM,Weymouth,Weymouth,AUK,--3-----,RL,901.0,NaN,3702S 17452E,NaN
27693,NaN,NZ,YGC,Spring Creek,Spring Creek,MBH,--3-----,RL,201.0,NaN,4128S 17358E,NaN
27694,NaN,NZ,ZNE,Riverlands,Riverlands,MBH,--3-----,RL,1307.0,NaN,3332S 01836E,NaN
27695,NaN,NZ,ZQN,Queenstown,Queenstown,OTA,---4----,AC,9601.0,NaN,NaN,NaN

In [26]:
df3 = pd.read_csv(file_path3)
df3

,Unnamed: 0,OM,Unnamed: 2,.OMAN,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,OM,ALA,Al Azaiba,Al Azaiba,MA,--3-----,RL,1301.0,NaN,2336S 05832E,NaN
1,NaN,OM,AMR,Al'Amrat,Al'Amrat,MA,--3-----,RL,1701.0,NaN,2331N 05829E,NaN
2,NaN,OM,AMZ,Al Mazunah,Al Mazunah,ZU,--3--6--,AM,2007.0,NaN,1750N 05238E,NaN
3,NaN,OM,BID,Bidbid,Bidbid,DA,--3-----,RL,1801.0,NaN,2324N 05807E,NaN
4,NaN,OM,BKK,Barka,Barka,BA,--3-----,RL,1407.0,NaN,2342N 05733E,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
33991,NaN,ZW,WKI,Hwange,Hwange,NaN,---4----,AI,1.0,NaN,NaN,NaN
33992,NaN,ZW,Z45,Chinhoyi,Chinhoyi,MW,--3-----,RL,1307.0,NaN,1722S 03012E,NaN
33993,NaN,ZW,ZMW,Selous,Selous,MW,--3-----,RL,1407.0,NaN,1805S 03027E,NaN
33994,NaN,ZW,ZMZ,Zimbabwe,Zimbabwe,MV,1-3-----,RL,1401.0,NaN,2016S 03055E,NaN
33995,NaN,ZW,ZVS,Zvishavane,Zvishavane,MI,--3-----,RL,1207.0,NaN,2020S 03002E,NaN

In [27]:
# Finding the number of rows and columns in each file
print("First Dataset: ", df1.shape)
print("Second Dataset: ", df2.shape)
print("Third Dataset: ", df3.shape)

First Dataset:  (54838, 12)
Second Dataset:  (27696, 12)
Third Dataset:  (33996, 12)

In [28]:
# In order to combine the dataset, we should combine/concatenate the value, 1st. 
df_combine = pd.concat([df1, df2, df3], ignore_index=True, axis=0)
df_combine

,Unnamed: 0,AD,Unnamed: 2,.ANDORRA,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,GA,.GABON,OM,.OMAN
0,NaN,AD,ALV,Andorra la Vella,Andorra la Vella,NaN,--34-6--,AI,601.0,NaN,4230N 00131E,NaN,NaN,NaN,NaN,NaN
1,NaN,AD,CAN,Canillo,Canillo,NaN,--3-----,RL,307.0,NaN,4234N 00135E,NaN,NaN,NaN,NaN,NaN
2,NaN,AD,EAC,Escàs,Escas,04,--3-----,RL,1407.0,NaN,4233N 00131E,NaN,NaN,NaN,NaN,NaN
3,NaN,AD,ENC,Encamp,Encamp,NaN,--3-----,RL,307.0,NaN,4232N 00134E,NaN,NaN,NaN,NaN,NaN
4,NaN,AD,ESC,Escaldes-Engordany,Escaldes-Engordany,NaN,--3-----,RL,307.0,NaN,4231N 00133E,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116525,NaN,NaN,WKI,NaN,Hwange,NaN,---4----,AI,1.0,NaN,NaN,NaN,NaN,NaN,ZW,Hwange
116526,NaN,NaN,Z45,NaN,Chinhoyi,MW,--3-----,RL,1307.0,NaN,1722S 03012E,NaN,NaN,NaN,ZW,Chinhoyi
116527,NaN,NaN,ZMW,NaN,Selous,MW,--3-----,RL,1407.0,NaN,1805S 03027E,NaN,NaN,NaN,ZW,Selous
116528,NaN,NaN,ZMZ,NaN,Zimbabwe,MV,1-3-----,RL,1401.0,NaN,2016S 03055E,NaN,NaN,NaN,ZW,Zimbabwe
116529,NaN,NaN,ZVS,NaN,Zvishavane,MI,--3-----,RL,1207.0,NaN,2020S 03002E,NaN,NaN,NaN,ZW,Zvishavane

In [29]:
print("Combined Dataset: ", df_combine.shape)

Combined Dataset:  (116530, 16)

In [31]:
# Converting the dataset to CSV file
df_combine.to_csv('C:\\Users\\Sheewakoti_Manish\\Documents\\My-Codes\\Sharp-Blue-Tasks\\Day01\\Task1\\combine_df_output.csv', index=False)

In [32]:
output_file = r'C:\\Users\\Sheewakoti_Manish\\Documents\\My-Codes\\Sharp-Blue-Tasks\\Day01\\Task1\\combine_df_output.csv'

In [33]:
df_output = pd.read_csv(output_file)
df_output

C:\Users\Sheewakoti_Manish\AppData\Local\Temp\ipykernel_3568\831463834.py:1: DtypeWarning: Columns (0: AD, 1: .ANDORRA, 2: GA, 3: .GABON, 4: OM, 5: .OMAN) have mixed types. Specify dtype option on import or set low_memory=False.
  df_output = pd.read_csv(output_file)

,Unnamed: 0,AD,Unnamed: 2,.ANDORRA,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,GA,.GABON,OM,.OMAN
0,NaN,AD,ALV,Andorra la Vella,Andorra la Vella,NaN,--34-6--,AI,601.0,NaN,4230N 00131E,NaN,NaN,NaN,NaN,NaN
1,NaN,AD,CAN,Canillo,Canillo,NaN,--3-----,RL,307.0,NaN,4234N 00135E,NaN,NaN,NaN,NaN,NaN
2,NaN,AD,EAC,Escàs,Escas,04,--3-----,RL,1407.0,NaN,4233N 00131E,NaN,NaN,NaN,NaN,NaN
3,NaN,AD,ENC,Encamp,Encamp,NaN,--3-----,RL,307.0,NaN,4232N 00134E,NaN,NaN,NaN,NaN,NaN
4,NaN,AD,ESC,Escaldes-Engordany,Escaldes-Engordany,NaN,--3-----,RL,307.0,NaN,4231N 00133E,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116525,NaN,NaN,WKI,NaN,Hwange,NaN,---4----,AI,1.0,NaN,NaN,NaN,NaN,NaN,ZW,Hwange
116526,NaN,NaN,Z45,NaN,Chinhoyi,MW,--3-----,RL,1307.0,NaN,1722S 03012E,NaN,NaN,NaN,ZW,Chinhoyi
116527,NaN,NaN,ZMW,NaN,Selous,MW,--3-----,RL,1407.0,NaN,1805S 03027E,NaN,NaN,NaN,ZW,Selous
116528,NaN,NaN,ZMZ,NaN,Zimbabwe,MV,1-3-----,RL,1401.0,NaN,2016S 03055E,NaN,NaN,NaN,ZW,Zimbabwe
116529,NaN,NaN,ZVS,NaN,Zvishavane,MI,--3-----,RL,1207.0,NaN,2020S 03002E,NaN,NaN,NaN,ZW,Zvishavane

In [35]:
df_output.shape

(116530, 16)